CREATE OR REPLACE PROCEDURE GET_USERS(
 --- カーソル  アウトプット用
    RESULT_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN RESULT_CURSOR FOR
        SELECT
            *
        FROM
            TEST01_USERS;
END GET_USERS;