CREATE OR REPLACE PROCEDURE UPDATE_USER(
    USER_ID IN NUMBER,
    NEW_NAME IN VARCHAR2,
    NEW_EMAIL IN VARCHAR2
) AS
BEGIN
 --- アップデート文
    UPDATE TEST01_USERS
    SET
        NAME = NEW_NAME,
        EMAIL = NEW_EMAIL
    WHERE
        ID = USER_ID;
END UPDATE_USER;